"""The T0 shape declarations render validator and contract consumers."""

from pathlib import Path
import tempfile
import unittest

from tools import render_shapes


ROOT = Path(__file__).resolve().parents[1]


class ShapeRenderTest(unittest.TestCase):
    def test_declarations_have_generated_validator_and_contract_consumers(self):
        self.assertTrue(render_shapes.declarations())
        rendered = render_shapes.render_validator()
        self.assertIn("GENERATED BY tools/render_shapes.py", rendered)
        for name in render_shapes.declarations():
            self.assertIn(name, rendered)
        for contract in render_shapes.contracts():
            section = render_shapes.render_contract(contract)
            self.assertIn("GENERATED BY tools/render_shapes.py", section)
            self.assertIn(contract, section)

    def test_render_check_detects_a_hand_edit(self):
        with tempfile.TemporaryDirectory() as directory:
            target = Path(directory) / "generated.py"
            target.write_text(render_shapes.render_validator() + "hand edit\n", encoding="utf-8")
            self.assertFalse(render_shapes.validator_is_current(target))

    def test_contract_render_is_closed_over_declaration(self):
        for name in render_shapes.declarations():
            declaration = render_shapes.declaration(name)
            self.assertTrue(declaration["fields"])
            self.assertTrue(declaration["contract"])
            rendered = render_shapes.render_contract(declaration["contract"])
            for field in declaration["fields"]:
                self.assertIn(f"`{field}`", rendered)


if __name__ == "__main__":
    unittest.main()
