"""Declared-dependency and host-mirror boundary checks."""

import sys
import unittest

from .source_roster_support import (
    DESCRIPTION_BUDGET,
    HOST_MIRROR,
    OWNER_SKILL,
    PROJECT_ROOT,
    frontmatter_description,
)
from .support import (
    STANDARD_LIBRARY_IMPORTS,
    THIRD_PARTY_SURFACES,
    absolute_imports,
    declared_import_names,
    imports_naming,
    outside_the_standard_library,
    package_sources,
)

class DeclaredDependenciesOnlyTest(unittest.TestCase):
    """Criterion 2, dependency half: nothing undeclared, on the 3.9 floor.

    The stdlib-only bar was lifted on 2026-09-02 (`docs/custom-workflow-
    authoring.md`, Dependencies): a ring item uses the libraries it needs and
    declares them in `requirements.txt` beside its manifest. What survives is
    the enumeration -- every module the package takes from outside itself is
    spelled out, and every one the interpreter does not answer from its own
    standard library has to be one the declaration accounts for. An import
    that is neither is a dependency nobody promised to install.
    """

    def test_the_package_takes_exactly_these_modules_from_outside_itself(self):
        taken = set()
        for path in package_sources():
            taken |= absolute_imports(path)

        self.assertEqual(tuple(sorted(taken)), STANDARD_LIBRARY_IMPORTS)

    def test_every_one_outside_the_stdlib_is_declared_beside_the_manifest(self):
        undeclared = [
            (name, origin)
            for name, origin in outside_the_standard_library(STANDARD_LIBRARY_IMPORTS)
            if name not in declared_import_names()
        ]

        self.assertEqual(undeclared, [])

    def test_the_floor_this_was_resolved_against_is_the_declared_one(self):
        # The resolution above is a fact about the interpreter that ran it, so
        # the interpreter is asserted rather than assumed.
        self.assertEqual(sys.version_info[:2], (3, 9))

    def test_no_module_names_an_sdk_a_driver_or_a_downloader(self):
        self.assertEqual(imports_naming(package_sources(), THIRD_PARTY_SURFACES), [])



class TheHostMirrorResolvesFromAnyCheckoutTest(unittest.TestCase):
    """The generated ring adapter's pointer lands on the owner, wherever the clone is.

    The mirror is generated by `orchflows sync` (`scripts/orchflows_adapters.py`)
    and committed — `install.py --project` writes no `.claude` — so an absolute
    path in it would be a path to one machine's filesystem and would resolve
    nowhere else: another user, another OS, another repository name, and
    nowhere at all at a revision built in a worktree. The generated body
    carries a repository-relative pointer instead (`orchflows_adapters.
    pointer_for`), never a preprocessing construct
    (`docs/custom-workflow-authoring.md:126`), and this is the check that the
    path it carries actually reaches the owner from wherever the checkout root
    is — the property the byte-exact pin on the whole generated body,
    `tests/test_ring_adapters.py`'s `CommittedProofTests`, does not itself
    state.

    Skipped rather than failed when the pair is not where a project-scope item
    puts them, because the item can be read from a copy and this suite's
    reliability bar is that it passes offline from anywhere.
    """

    def setUp(self):
        if not HOST_MIRROR.exists():
            self.skipTest("no project-scope host mirror beside this item")

    def test_the_pointer_is_relative_and_reaches_the_owner(self):
        body = HOST_MIRROR.read_text(encoding="utf-8")
        pointer_lines = [
            line
            for line in body.splitlines()
            if line.startswith("Read ") and line.endswith(" and follow it exactly.")
        ]

        self.assertEqual(len(pointer_lines), 1)
        target = pointer_lines[0][len("Read "):-len(" and follow it exactly.")]
        self.assertFalse(target.startswith("/"), "a committed stub names one machine")
        self.assertFalse(target[1:2] == ":", "a committed stub names one machine")
        # Resolved the way the pointer is generated: project-root-relative
        # (`orchflows_adapters.pointer_for`), not relative to the stub's own
        # directory — the stub and the owner do not share a parent.
        self.assertEqual((PROJECT_ROOT / target).resolve(), OWNER_SKILL)

    def test_no_line_of_the_stub_names_one_machine(self):
        # The pointer line is not the only place a path could arrive, so
        # absoluteness is checked over the whole stub and not over the pointer
        # alone: a path spelled anywhere else in the body would be the same
        # defect wearing prose.
        body = HOST_MIRROR.read_text(encoding="utf-8")

        for token in body.replace("`", " ").split():
            with self.subTest(token=token):
                self.assertFalse(token.lstrip("@").startswith("/"))
                self.assertNotRegex(token.lstrip("@"), r"^[A-Za-z]:[\\/]")

    def test_the_owner_and_the_mirror_describe_the_item_with_one_string(self):
        # A Claude host routes on the mirror's copy and never reads the owner's,
        # so drift here costs the item every invocation while both files still
        # read correctly on their own — the one failure nobody thinks to check.
        # Nothing else pins the pair: the assertion above is about the include,
        # and `tools/validate.py` does not walk this tree.
        owner = frontmatter_description(OWNER_SKILL)

        self.assertIsNotNone(owner, "the owner's frontmatter names no description")
        self.assertEqual(frontmatter_description(HOST_MIRROR), owner)
        self.assertLessEqual(len(owner), DESCRIPTION_BUDGET)
