#!/usr/bin/env python3
"""Host adapters for ring items: inert, generated, and removable.

The installer's rendering pipeline pointed at the rings, reading the same
host records (`installer/host_adapters/*.json`), so no second spelling of
"where a Claude skill goes" can exist. Home-ring items render into the
user's host surfaces on `orchflows sync`; project-ring items render into
the project's own committed surfaces and travel with the repository.

Every generated body is inert: legal frontmatter and a pointer or a
command, never a preprocessing construct. A skill body that ran a command
before the model saw anything would make a cloned repository an execution
surface, and orchflows cannot gate a host's own loading of a committed
`.claude/skills/`.

Standards get no adapter: both are stamped on a ticket and never
invoked by name, so either in a host's skill list would be a name that
cannot be called crowding the names that can. `ADAPTED_KINDS` decides that
for every kind at once.
"""

from __future__ import annotations

import json
import os
import re
import shutil
from pathlib import Path
from typing import Dict, List, Optional, Tuple

try:
    from scripts import rings
except ImportError:  # pragma: no cover - direct/installed flat script path
    import rings


HOSTS = ("claude", "codex", "grok")
ADAPTED_KINDS = ("skill", "workflow")
# One line every generated adapter carries: `sync` deletes exactly the
# files in a surface that carry it and no longer have a ring item.
MARKER = "<!-- orchflows ring adapter: generated by `orchflows sync`; edits are overwritten -->"
# The cross-vendor project surface. No host record owns it because it is
# not one host's path: `.agents/skills/` is the convergence several agent
# CLIs read, and this module is its one owner here.
AGENTS_SURFACE = ".agents"
AGENTS_ITEM = "skills/{name}/SKILL.md"
# The manual-invocation-only flag every workflow adapter carries.
MANUAL_ONLY_KEY = "disable-model-invocation"
_FRONTMATTER_RE = re.compile(r"(?s)\A---\r?\n(.*?)\r?\n---\r?\n?")


def host_records(lib: Optional[Path] = None) -> Dict[str, dict]:
    """The rendered host records, from the checkout or the installed lib."""

    root = Path(lib) if lib is not None else rings.lib_root()
    records = {}
    for host in HOSTS:
        path = root / "installer" / "host_adapters" / f"{host}.json"
        try:
            document = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, UnicodeDecodeError, ValueError) as error:
            raise rings.RingError(
                "host-record-unreadable", f"unreadable host record {path}: {error}",
            ) from error
        records[host] = document["host"]
    return records


def detected(records: Dict[str, dict]) -> List[str]:
    """The hosts whose CLI is runnable here, by the record's own candidates."""

    return [
        host for host in HOSTS
        if any(shutil.which(name) for name in records[host]["cli_candidates"])
    ]


def _host_home(record: dict) -> Path:
    home = record["home"]
    override = os.environ.get(home["environment"], "").strip()
    return Path(override).expanduser() if override else Path.home() / home["default"]


def _item_path(record: dict, item: str, root: Path, name: str) -> Path:
    return root / Path(record["installed_items"][item].format(name=name))


def frontmatter_of(text: str) -> Dict[str, str]:
    """The item's declared frontmatter as ordered scalar pairs."""

    match = _FRONTMATTER_RE.match(text)
    if match is None:
        return {}
    fields = {}
    for line in match.group(1).splitlines():
        key, separator, value = line.partition(":")
        if separator and key.strip() and not key.startswith(" "):
            fields[key.strip()] = value.strip()
    return fields


def legal_frontmatter(fields: Dict[str, str], record: dict) -> str:
    """The item's frontmatter narrowed to what this host declares legal."""

    legal = [key for key in record["frontmatter"]["legal_keys"] if key in fields]
    lines = ["---"] + [f"{key}: {fields[key]}" for key in legal] + ["---"]
    return "\n".join(lines) + "\n"


def body_for(kind: str, name: str, pointer: str) -> str:
    """The inert body: what to read, or what to run. Never both, never code."""

    if kind == "workflow":
        return (
            f"`{name}` is a workflow skill: prose that opens a frame and calls "
            f"callables. Its one body is {pointer}.\n\n"
            "Read that file whole and invoke the skill by following it "
            "exactly: its Require names what the caller supplies, its call "
            "lines are the commands to run, and its Return is the close. A "
            "workflow is only ever invoked by name.\n"
        )
    return f"Read {pointer} and follow it exactly.\n"


def pointer_for(item: Path, project: Optional[Path]) -> str:
    """How the adapter names the item it points at."""

    if project is not None:
        try:
            return item.relative_to(project).as_posix()
        except ValueError:  # pragma: no cover - a ring outside its own project
            pass
    return str(item)


def render(kind: str, name: str, item: Path, record: dict, pointer: str = None) -> str:
    """One generated adapter: legal frontmatter, the marker, then the body."""

    try:
        text = item.read_text(encoding="utf-8-sig")
    except (OSError, UnicodeDecodeError) as error:
        raise rings.RingError("item-unreadable", f"unreadable {kind} {item}: {error}") from error
    fields = dict(frontmatter_of(text))
    fields.setdefault("name", name)
    if kind == "workflow":
        # Forced, never inherited. A workflow's prose executes as
        # orchestrator reasoning rather than inside a sealed child prompt,
        # so a host firing one on its own reading of a description opens
        # that surface without anybody asking.
        fields[MANUAL_ONLY_KEY] = "true"
    return (
        legal_frontmatter(fields, record)
        + "\n"
        + MARKER
        + "\n\n"
        + body_for(kind, name, str(item) if pointer is None else pointer)
    )


def _surfaces(scope: str, records: Dict[str, dict], project: Optional[Path]) -> List[Tuple[str, Path, str]]:
    """``(surface id, root, installed-item template key)`` for one scope."""

    if scope == "home":
        return [
            (host, _host_home(records[host]), "skill")
            for host in detected(records)
        ]
    if project is None:
        raise rings.RingError("no-project", "project-scope rendering needs a project root")
    return [
        ("claude", project / records["claude"]["home"]["default"], "skill"),
        ("agents", project / AGENTS_SURFACE, "agents"),
    ]


def _destination(surface: str, record, root: Path, item_key: str, kind: str, name: str) -> Path:
    # A ring may hold a skill and a workflow of one name, and both render
    # through the same "skill" surface, so a destination keyed on name
    # alone collapses them onto one path. The slug carries kind into the
    # path while `render()` still gets the true, unsuffixed name.
    slug = f"{name}-workflow" if kind == "workflow" else name
    if item_key == "agents":
        return root / Path(AGENTS_ITEM.format(name=slug))
    return _item_path(record, "skill", root, slug)


def plan(scope: str, *, project: Optional[Path] = None, lib: Optional[Path] = None, **overrides):
    """``[(destination, text)]`` for every adaptable item in one ring."""

    records = host_records(lib)
    ring = "project" if scope == "project" else "home"
    surfaces = _surfaces(ring, records, project)
    if ring == "project" and project is not None:
        overrides = {**overrides, "project": project}
    written = []
    for record in rings.inventory(ADAPTED_KINDS, lib=lib, **overrides):
        if record["ring"] != ring or record.get("reserved"):
            continue
        item = Path(str(record["path"]))
        pointer = pointer_for(item, project if ring == "project" else None)
        for surface, root, item_key in surfaces:
            # `.agents/` is read by several CLIs and named by no host
            # record, so it takes Claude's legal-key set: the widest here.
            host_record = records.get(surface) or records["claude"]
            text = render(str(record["kind"]), str(record["name"]), item, host_record, pointer)
            destination = _destination(
                surface, host_record, root, item_key, str(record["kind"]), str(record["name"]),
            )
            written.append((destination, text))
    return written


def stale(scope: str, keep, *, project: Optional[Path] = None, lib: Optional[Path] = None) -> List[Path]:
    """Generated adapters in this scope's surfaces with no ring item left."""

    records = host_records(lib)
    ring = "project" if scope == "project" else "home"
    kept = {str(path) for path in keep}
    found = []
    for _surface, root, _item_key in _surfaces(ring, records, project):
        # Every surface spells a skill as `skills/<name>/SKILL.md`, so one
        # glob finds the generated files in all of them.
        base = root / "skills"
        if not base.is_dir():
            continue
        for path in sorted(base.glob("*/SKILL.md")):
            if str(path) in kept:
                continue
            try:
                if MARKER in path.read_text(encoding="utf-8-sig"):
                    found.append(path)
            except (OSError, UnicodeDecodeError):
                continue
    return found


def write(scope: str, *, project: Optional[Path] = None, lib: Optional[Path] = None, **overrides) -> dict:
    """Render one ring's adapters and remove the ones it no longer owns."""

    entries = plan(scope, project=project, lib=lib, **overrides)
    for destination, text in entries:
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_bytes(text.encode("utf-8"))
    removed = stale(scope, [path for path, _ in entries], project=project, lib=lib)
    for path in removed:
        path.unlink()
        parent = path.parent
        if not any(parent.iterdir()):
            parent.rmdir()
    return {
        "written": [str(path) for path, _ in entries],
        "removed": [str(path) for path in removed],
    }


__all__ = (
    "ADAPTED_KINDS", "AGENTS_ITEM", "AGENTS_SURFACE", "HOSTS", "MANUAL_ONLY_KEY",
    "MARKER",
    "body_for", "detected", "frontmatter_of", "host_records",
    "legal_frontmatter", "plan", "pointer_for", "render", "stale", "write",
)
