"""Generated T0 shape data; edit contracts/shapes.json instead."""
# GENERATED BY tools/render_shapes.py; DO NOT EDIT.
from __future__ import annotations

SHAPES = {'dispatch_attempt': {'contract': 'dispatch.md',
                      'fields': ('assignment_seal',
                                 'dispatch_id',
                                 'lease_expires_at',
                                 'opened_at',
                                 'outcome_record_id',
                                 'owner',
                                 'records',
                                 'state',
                                 'retired_at',
                                 'retirement',
                                 'replaced_at',
                                 'replaced_by',
                                 'replacement',
                                 'replaces'),
                      'required': ('assignment_seal',
                                   'dispatch_id',
                                   'lease_expires_at',
                                   'opened_at',
                                   'outcome_record_id',
                                   'owner',
                                   'records',
                                   'state'),
                      'values': {'state': ('live', 'retired', 'replaced')}},
 'dispatch_outcome': {'contract': 'dispatch.md',
                      'fields': ('protocol',
                                 'run',
                                 'id',
                                 'assignment_seal',
                                 'dispatch_id',
                                 'outcome_record_id',
                                 'by',
                                 'status',
                                 'evidence'),
                      'required': ('protocol',
                                   'run',
                                   'id',
                                   'assignment_seal',
                                   'dispatch_id',
                                   'outcome_record_id',
                                   'by',
                                   'status',
                                   'evidence'),
                      'values': {'status': ('complete',
                                            'blocked',
                                            'stalled',
                                            'limited',
                                            'failed',
                                            'suspended')}},
 'dispatch_outcome_evidence': {'contract': 'dispatch.md',
                               'fields': ('Result', 'Verification', 'Feedback', 'Risks', 'Handoff'),
                               'required': ('Result',
                                            'Verification',
                                            'Feedback',
                                            'Risks',
                                            'Handoff'),
                               'values': {}},
 'dispatch_packet': {'contract': 'dispatch.md',
                     'fields': ('protocol',
                                'source',
                                'dispatch_id',
                                'assignment_seal',
                                'outcome_record_id',
                                'lease_expires_at',
                                'executor',
                                'role',
                                'profile',
                                'assigned_name',
                                'reply_to',
                                'workspace',
                                'pack',
                                'independence',
                                'isolation',
                                'admission',
                                'prompt',
                                'review_kind',
                                'form',
                                'durability',
                                'reference',
                                'inline'),
                     'required': ('protocol',
                                  'source',
                                  'dispatch_id',
                                  'assignment_seal',
                                  'outcome_record_id',
                                  'lease_expires_at',
                                  'executor',
                                  'role',
                                  'profile',
                                  'assigned_name',
                                  'reply_to',
                                  'workspace',
                                  'pack',
                                  'independence',
                                  'isolation',
                                  'admission',
                                  'prompt',
                                  'review_kind',
                                  'form',
                                  'durability'),
                     'values': {'durability': ('ticket', 'ephemeral'),
                                'form': ('reference', 'inline'),
                                'review_kind': ('critique', 'repair', 'verify', 'null')}},
 'dispatch_receipt': {'contract': 'dispatch.md',
                      'fields': ('protocol',
                                 'outcome',
                                 'dispatch_id',
                                 'assignment_seal',
                                 'form',
                                 'durability',
                                 'state_sink_checked'),
                      'required': ('protocol',
                                   'outcome',
                                   'dispatch_id',
                                   'assignment_seal',
                                   'form',
                                   'durability',
                                   'state_sink_checked'),
                      'values': {'durability': ('ticket',),
                                 'outcome': ('accepted',),
                                 'protocol': ('orchflows.dispatch.v1',)}},
 'dispatch_record': {'contract': 'dispatch.md',
                     'fields': ('committed_at', 'content', 'kind', 'record_id', 'success'),
                     'required': ('committed_at', 'content', 'kind', 'record_id', 'success'),
                     'values': {'kind': ('generic',
                                         'packet',
                                         'receipt',
                                         'result',
                                         'outcome',
                                         'join',
                                         'lifecycle')}},
 'dispatch_state': {'contract': 'dispatch.md',
                    'fields': ('protocol', 'attempts'),
                    'required': ('protocol', 'attempts'),
                    'values': {'protocol': ('orchflows.dispatch.v1',)}},
 'executor_result': {'contract': 'result.md',
                     'fields': ('assignment_seal',
                                'body',
                                'mode',
                                'operation',
                                'section',
                                'writer'),
                     'required': ('assignment_seal',
                                  'body',
                                  'mode',
                                  'operation',
                                  'section',
                                  'writer'),
                     'values': {'mode': ('write', 'append', 'replace'), 'operation': ('result',)}},
 'pack_cells': {'contract': 'pack-signature.md',
                'fields': ('slicing',
                           'workspace',
                           'required_spec_fields',
                           'craft',
                           'adapter',
                           'stages',
                           'assembly',
                           'lens',
                           'evidence'),
                'required': ('slicing',
                             'workspace',
                             'required_spec_fields',
                             'craft',
                             'adapter',
                             'stages',
                             'assembly',
                             'lens',
                             'evidence'),
                'values': {'assembly': ('none', 'stage name')}},
 'review_criterion': {'contract': 'work-item.md',
                      'fields': ('identity', 'lens', 'order', 'ticket'),
                      'required': ('identity', 'lens', 'order', 'ticket'),
                      'values': {}},
 'review_critique': {'contract': 'work-item.md',
                     'fields': ('accepted', 'adjudicated_by', 'artifact', 'findings', 'lens'),
                     'required': ('accepted', 'adjudicated_by', 'artifact', 'findings', 'lens'),
                     'values': {}},
 'review_finding': {'contract': 'work-item.md',
                    'fields': ('blocking',
                               'class',
                               'evidence',
                               'goal_impact',
                               'id',
                               'repair',
                               'summary'),
                    'required': ('blocking',
                                 'class',
                                 'evidence',
                                 'goal_impact',
                                 'id',
                                 'repair',
                                 'summary'),
                    'values': {}},
 'review_gate_plan': {'contract': 'work-item.md',
                      'fields': ('artifact',
                                 'criteria',
                                 'isolation',
                                 'mode',
                                 'pack',
                                 'root',
                                 'workspace'),
                      'required': ('artifact',
                                   'criteria',
                                   'isolation',
                                   'mode',
                                   'pack',
                                   'root',
                                   'workspace'),
                      'values': {'mode': ('gate', 'checker')}},
 'review_record_common': {'contract': 'work-item.md',
                          'fields': ('identity', 'kind', 'predecessor', 'protocol'),
                          'required': ('identity', 'kind', 'predecessor', 'protocol'),
                          'values': {'kind': ('GatePlan',
                                              'CritiqueAdjudication',
                                              'RepairOutcome',
                                              'Verification')}},
 'review_repair': {'contract': 'work-item.md',
                   'fields': ('accepted', 'artifact', 'by', 'input_artifact', 'no_op', 'result'),
                   'required': ('accepted', 'artifact', 'by', 'input_artifact', 'no_op', 'result'),
                   'values': {}},
 'review_state': {'contract': 'work-item.md',
                  'fields': ('protocol', 'records'),
                  'required': ('protocol', 'records'),
                  'values': {'protocol': ('orchflows.review.v1',)}},
 'review_verification': {'contract': 'work-item.md',
                         'fields': ('artifact', 'by', 'evidence', 'verdict', 'covers'),
                         'required': ('artifact', 'by', 'evidence', 'verdict'),
                         'values': {'verdict': ('PASS', 'FAIL', 'UNVERIFIED')}},
 'ticket_assignment_sections': {'contract': 'work-item.md',
                                'fields': ('Goal', 'Context', 'Suggested files'),
                                'required': ('Goal', 'Context'),
                                'values': {}},
 'ticket_frontmatter': {'contract': 'work-item.md',
                        'fields': ('id',
                                   'run',
                                   'status',
                                   'admission',
                                   'executor',
                                   'sequence',
                                   'pack',
                                   'profile',
                                   'independence',
                                   'depends_on',
                                   'isolation',
                                   'bound',
                                   'claimed_by',
                                   'claimed_at',
                                   'checked_by',
                                   'root_generation',
                                   'cut_generation',
                                   'assignment_seal',
                                   'workspace_branch',
                                   'workspace_baseline',
                                   'workspace_path',
                                   'dispatch_v1',
                                   'review_order',
                                   'review_v1',
                                   'review_stage',
                                   'review_kind'),
                        'required': ('id', 'run', 'status', 'executor', 'depends_on', 'bound'),
                        'values': {'review_kind': ('critique', 'repair', 'verify', 'null'),
                                   'status': ('pending',
                                              'ready',
                                              'claimed',
                                              'suspended',
                                              'complete',
                                              'blocked',
                                              'stalled',
                                              'failed',
                                              'limited')}},
 'verdict_criterion': {'contract': 'verdict.md',
                       'fields': ('verdict', 'oracle', 'oracle_class', 'evidence', 'covers'),
                       'required': ('verdict', 'oracle', 'oracle_class', 'evidence', 'covers'),
                       'values': {'oracle_class': ('deterministic', 'judged', 'evidence'),
                                  'verdict': ('PASS', 'FAIL', 'UNVERIFIED')}},
 'worklog_view': {'contract': 'worklog.md',
                  'fields': ('goal', 'iterations', 'failed_approaches', 'queued_scope', 'terminal'),
                  'required': ('goal',
                               'iterations',
                               'failed_approaches',
                               'queued_scope',
                               'terminal'),
                  'values': {}}}

DISPATCH_STATE_FIELDS = tuple(SHAPES['dispatch_state']['fields'])
DISPATCH_STATE_REQUIRED = frozenset(SHAPES['dispatch_state']['required'])
DISPATCH_STATE_VALUES = SHAPES['dispatch_state']['values']

DISPATCH_ATTEMPT_FIELDS = tuple(SHAPES['dispatch_attempt']['fields'])
DISPATCH_ATTEMPT_REQUIRED = frozenset(SHAPES['dispatch_attempt']['required'])
DISPATCH_ATTEMPT_VALUES = SHAPES['dispatch_attempt']['values']

DISPATCH_RECORD_FIELDS = tuple(SHAPES['dispatch_record']['fields'])
DISPATCH_RECORD_REQUIRED = frozenset(SHAPES['dispatch_record']['required'])
DISPATCH_RECORD_VALUES = SHAPES['dispatch_record']['values']

DISPATCH_PACKET_FIELDS = tuple(SHAPES['dispatch_packet']['fields'])
DISPATCH_PACKET_REQUIRED = frozenset(SHAPES['dispatch_packet']['required'])
DISPATCH_PACKET_VALUES = SHAPES['dispatch_packet']['values']

DISPATCH_RECEIPT_FIELDS = tuple(SHAPES['dispatch_receipt']['fields'])
DISPATCH_RECEIPT_REQUIRED = frozenset(SHAPES['dispatch_receipt']['required'])
DISPATCH_RECEIPT_VALUES = SHAPES['dispatch_receipt']['values']

DISPATCH_OUTCOME_FIELDS = tuple(SHAPES['dispatch_outcome']['fields'])
DISPATCH_OUTCOME_REQUIRED = frozenset(SHAPES['dispatch_outcome']['required'])
DISPATCH_OUTCOME_VALUES = SHAPES['dispatch_outcome']['values']

DISPATCH_OUTCOME_EVIDENCE_FIELDS = tuple(SHAPES['dispatch_outcome_evidence']['fields'])
DISPATCH_OUTCOME_EVIDENCE_REQUIRED = frozenset(SHAPES['dispatch_outcome_evidence']['required'])
DISPATCH_OUTCOME_EVIDENCE_VALUES = SHAPES['dispatch_outcome_evidence']['values']

REVIEW_STATE_FIELDS = tuple(SHAPES['review_state']['fields'])
REVIEW_STATE_REQUIRED = frozenset(SHAPES['review_state']['required'])
REVIEW_STATE_VALUES = SHAPES['review_state']['values']

REVIEW_RECORD_COMMON_FIELDS = tuple(SHAPES['review_record_common']['fields'])
REVIEW_RECORD_COMMON_REQUIRED = frozenset(SHAPES['review_record_common']['required'])
REVIEW_RECORD_COMMON_VALUES = SHAPES['review_record_common']['values']

REVIEW_GATE_PLAN_FIELDS = tuple(SHAPES['review_gate_plan']['fields'])
REVIEW_GATE_PLAN_REQUIRED = frozenset(SHAPES['review_gate_plan']['required'])
REVIEW_GATE_PLAN_VALUES = SHAPES['review_gate_plan']['values']

REVIEW_CRITERION_FIELDS = tuple(SHAPES['review_criterion']['fields'])
REVIEW_CRITERION_REQUIRED = frozenset(SHAPES['review_criterion']['required'])
REVIEW_CRITERION_VALUES = SHAPES['review_criterion']['values']

REVIEW_FINDING_FIELDS = tuple(SHAPES['review_finding']['fields'])
REVIEW_FINDING_REQUIRED = frozenset(SHAPES['review_finding']['required'])
REVIEW_FINDING_VALUES = SHAPES['review_finding']['values']

REVIEW_CRITIQUE_FIELDS = tuple(SHAPES['review_critique']['fields'])
REVIEW_CRITIQUE_REQUIRED = frozenset(SHAPES['review_critique']['required'])
REVIEW_CRITIQUE_VALUES = SHAPES['review_critique']['values']

REVIEW_REPAIR_FIELDS = tuple(SHAPES['review_repair']['fields'])
REVIEW_REPAIR_REQUIRED = frozenset(SHAPES['review_repair']['required'])
REVIEW_REPAIR_VALUES = SHAPES['review_repair']['values']

REVIEW_VERIFICATION_FIELDS = tuple(SHAPES['review_verification']['fields'])
REVIEW_VERIFICATION_REQUIRED = frozenset(SHAPES['review_verification']['required'])
REVIEW_VERIFICATION_VALUES = SHAPES['review_verification']['values']

TICKET_ASSIGNMENT_SECTIONS_FIELDS = tuple(SHAPES['ticket_assignment_sections']['fields'])
TICKET_ASSIGNMENT_SECTIONS_REQUIRED = frozenset(SHAPES['ticket_assignment_sections']['required'])
TICKET_ASSIGNMENT_SECTIONS_VALUES = SHAPES['ticket_assignment_sections']['values']

TICKET_FRONTMATTER_FIELDS = tuple(SHAPES['ticket_frontmatter']['fields'])
TICKET_FRONTMATTER_REQUIRED = frozenset(SHAPES['ticket_frontmatter']['required'])
TICKET_FRONTMATTER_VALUES = SHAPES['ticket_frontmatter']['values']

EXECUTOR_RESULT_FIELDS = tuple(SHAPES['executor_result']['fields'])
EXECUTOR_RESULT_REQUIRED = frozenset(SHAPES['executor_result']['required'])
EXECUTOR_RESULT_VALUES = SHAPES['executor_result']['values']

VERDICT_CRITERION_FIELDS = tuple(SHAPES['verdict_criterion']['fields'])
VERDICT_CRITERION_REQUIRED = frozenset(SHAPES['verdict_criterion']['required'])
VERDICT_CRITERION_VALUES = SHAPES['verdict_criterion']['values']

WORKLOG_VIEW_FIELDS = tuple(SHAPES['worklog_view']['fields'])
WORKLOG_VIEW_REQUIRED = frozenset(SHAPES['worklog_view']['required'])
WORKLOG_VIEW_VALUES = SHAPES['worklog_view']['values']

PACK_CELLS_FIELDS = tuple(SHAPES['pack_cells']['fields'])
PACK_CELLS_REQUIRED = frozenset(SHAPES['pack_cells']['required'])
PACK_CELLS_VALUES = SHAPES['pack_cells']['values']

def fields(name: str) -> tuple:
    """Return the declared field order for one shape."""
    return tuple(SHAPES[name]['fields'])

def required(name: str) -> frozenset:
    """Return the required fields for one shape."""
    return frozenset(SHAPES[name]['required'])
