"""Generated T0 shape data; edit contracts/shapes.json instead."""
# GENERATED BY tools/render_shapes.py; DO NOT EDIT.
from __future__ import annotations

CONSTANTS = {'dispatch_protocol': 'orchflows.dispatch.v1', 'launch_record_id': 'launch', 'outcome_record_id': 'outcome'}

SHAPES = {'dispatch_attempt': {'contract': 'dispatch.md',
                      'fields': ('assignment_seal',
                                 'dispatch_id',
                                 'lease_expires_at',
                                 'opened_at',
                                 'outcome_record_id',
                                 'owner',
                                 'records',
                                 'state',
                                 'workspace_path',
                                 'retired_at',
                                 'retirement',
                                 'replaced_at',
                                 'replaced_by',
                                 'replacement',
                                 'replaces'),
                      'required': ('assignment_seal', 'dispatch_id', 'lease_expires_at', 'opened_at', 'outcome_record_id', 'owner', 'records', 'state'),
                      'values': {'outcome_record_id': ('outcome',), 'state': ('live', 'retired', 'replaced')}},
 'dispatch_committed_record': {'contract': 'dispatch.md',
                               'fields': ('protocol', 'run', 'id', 'dispatch_id', 'record_id'),
                               'required': ('protocol', 'run', 'id', 'dispatch_id', 'record_id'),
                               'values': {}},
 'dispatch_join_content': {'contract': 'dispatch.md',
                           'fields': ('assignment_seal', 'dispatch_id', 'joined_by', 'operation', 'outcome_record_id'),
                           'required': ('assignment_seal', 'dispatch_id', 'joined_by', 'operation', 'outcome_record_id'),
                           'values': {}},
 'dispatch_join_success': {'contract': 'dispatch.md',
                           'fields': ('protocol', 'run', 'id', 'assignment_seal', 'dispatch_id', 'outcome_record_id', 'by', 'status', 'joined_at'),
                           'required': ('protocol', 'run', 'id', 'assignment_seal', 'dispatch_id', 'outcome_record_id', 'by', 'status', 'joined_at'),
                           'values': {'status': ('complete', 'blocked', 'stalled', 'limited', 'failed', 'suspended')}},
 'dispatch_launch': {'contract': 'dispatch.md',
                     'fields': ('host', 'verb', 'agent', 'model', 'effort', 'fields', 'prompt'),
                     'required': ('host', 'verb', 'agent', 'model', 'effort', 'fields', 'prompt'),
                     'values': {}},
 'dispatch_launch_record': {'contract': 'dispatch.md', 'fields': ('launch',), 'required': ('launch',), 'values': {}},
 'dispatch_outcome': {'contract': 'dispatch.md',
                      'fields': ('protocol', 'run', 'id', 'assignment_seal', 'dispatch_id', 'outcome_record_id', 'by', 'evidence'),
                      'required': ('protocol', 'run', 'id', 'assignment_seal', 'dispatch_id', 'outcome_record_id', 'by', 'evidence'),
                      'values': {}},
 'dispatch_record': {'contract': 'dispatch.md',
                     'fields': ('committed_at', 'content', 'kind', 'record_id', 'success'),
                     'required': ('committed_at', 'content', 'kind', 'record_id', 'success'),
                     'values': {'kind': ('generic', 'launch', 'result', 'outcome', 'join', 'lifecycle')}},
 'dispatch_replace_request': {'contract': 'dispatch.md',
                              'fields': ('assignment_seal', 'dispatch_id', 'lease_expires_at', 'operation', 'owner', 'replaces'),
                              'required': ('assignment_seal', 'dispatch_id', 'lease_expires_at', 'operation', 'owner', 'replaces'),
                              'values': {'operation': ('replace',)}},
 'dispatch_replacement_dispatch': {'contract': 'dispatch.md',
                                   'fields': ('protocol',
                                              'outcome',
                                              'run',
                                              'id',
                                              'dispatch_id',
                                              'record_id',
                                              'replaces',
                                              'assignment_seal',
                                              'lease_expires_at',
                                              'opened_at',
                                              'state'),
                                   'required': ('protocol',
                                                'outcome',
                                                'run',
                                                'id',
                                                'dispatch_id',
                                                'record_id',
                                                'replaces',
                                                'assignment_seal',
                                                'lease_expires_at',
                                                'opened_at',
                                                'state'),
                                   'values': {'outcome': ('replaced',), 'state': ('live',)}},
 'dispatch_result_projection': {'contract': 'dispatch.md',
                                'fields': ('protocol', 'run', 'id', 'path', 'by', 'assignment_seal', 'dispatch_id', 'record_id'),
                                'required': ('protocol', 'run', 'id', 'path', 'by', 'assignment_seal', 'dispatch_id', 'record_id'),
                                'values': {}},
 'dispatch_result_record': {'contract': 'dispatch.md',
                            'fields': ('assignment_seal', 'body', 'operation', 'writer'),
                            'required': ('assignment_seal', 'body', 'operation', 'writer'),
                            'values': {}},
 'dispatch_result_success': {'contract': 'dispatch.md', 'fields': ('result',), 'required': ('result',), 'values': {}},
 'dispatch_retire_request': {'contract': 'dispatch.md',
                             'fields': ('assignment_seal', 'dispatch_id', 'operation'),
                             'required': ('assignment_seal', 'dispatch_id', 'operation'),
                             'values': {'operation': ('retire',)}},
 'dispatch_retirement_dispatch': {'contract': 'dispatch.md',
                                  'fields': ('protocol', 'outcome', 'run', 'id', 'dispatch_id', 'record_id', 'retired_at', 'state'),
                                  'required': ('protocol', 'outcome', 'run', 'id', 'dispatch_id', 'record_id', 'retired_at', 'state'),
                                  'values': {'outcome': ('retired',), 'state': ('retired',)}},
 'dispatch_state': {'contract': 'dispatch.md',
                    'fields': ('protocol', 'attempts'),
                    'required': ('protocol', 'attempts'),
                    'values': {'protocol': ('orchflows.dispatch.v1',)}},
 'dispatch_stored_success': {'contract': 'dispatch.md', 'fields': ('committed_record',), 'required': ('committed_record',), 'values': {}},
 'dispatch_transition_success': {'contract': 'dispatch.md', 'fields': ('dispatch',), 'required': ('dispatch',), 'values': {}},
 'done_binding': {'contract': 'work-item.md', 'fields': ('form', 'value'), 'required': ('form', 'value'), 'values': {'form': ('command', 'check')}},
 'executor_result': {'contract': 'result.md',
                     'fields': ('assignment_seal', 'body', 'operation', 'writer'),
                     'required': ('assignment_seal', 'body', 'operation', 'writer'),
                     'values': {'operation': ('result',)}},
 'pack_cells': {'contract': 'pack-signature.md', 'fields': ('adapter', 'craft'), 'required': ('adapter', 'craft'), 'values': {}},
 'sheet_frontmatter': {'contract': 'sheet.md', 'fields': ('name', 'description', 'packs'), 'required': ('name', 'description', 'packs'), 'values': {}},
 'sheet_sections': {'contract': 'sheet.md', 'fields': ('Craft', 'Lens', 'Vocabulary'), 'required': ('Craft', 'Lens'), 'values': {}},
 'ticket_assignment_sections': {'contract': 'work-item.md', 'fields': ('Goal', 'Context', 'Details'), 'required': ('Goal', 'Context'), 'values': {}},
 'ticket_frontmatter': {'contract': 'work-item.md',
                        'fields': ('id',
                                   'run',
                                   'status',
                                   'admission',
                                   'executor',
                                   'pack',
                                   'pack_digest',
                                   'sheets',
                                   'sheet_digests',
                                   'skill',
                                   'skill_digest',
                                   'profile',
                                   'parent',
                                   'depends_on',
                                   'isolation',
                                   'bound',
                                   'frame',
                                   'done',
                                   'makes',
                                   'root_generation',
                                   'cut_generation',
                                   'assignment_seal',
                                   'workspace_branch',
                                   'workspace_baseline',
                                   'dispatch_v1'),
                        'required': ('id', 'run', 'status', 'executor', 'bound'),
                        'values': {'frame': ('true',),
                                   'makes': ('root', 'cut'),
                                   'status': ('pending', 'ready', 'claimed', 'suspended', 'complete', 'blocked', 'stalled', 'failed', 'limited')}},
 'verdict_criterion': {'contract': 'verdict.md',
                       'fields': ('verdict', 'oracle', 'oracle_class', 'evidence', 'covers'),
                       'required': ('verdict', 'oracle', 'oracle_class', 'evidence', 'covers'),
                       'values': {'oracle_class': ('deterministic', 'judged', 'evidence'), 'verdict': ('PASS', 'FAIL', 'UNVERIFIED')}},
 'worklog_view': {'contract': 'worklog.md',
                  'fields': ('goal', 'iterations', 'failed_approaches', 'queued_scope', 'terminal'),
                  'required': ('goal', 'iterations', 'failed_approaches', 'queued_scope', 'terminal'),
                  'values': {}}}

DISPATCH_PROTOCOL = CONSTANTS['dispatch_protocol']
LAUNCH_RECORD_ID = CONSTANTS['launch_record_id']
OUTCOME_RECORD_ID = CONSTANTS['outcome_record_id']

DISPATCH_STATE_FIELDS = tuple(SHAPES['dispatch_state']['fields'])
DISPATCH_STATE_REQUIRED = frozenset(SHAPES['dispatch_state']['required'])
DISPATCH_STATE_VALUES = SHAPES['dispatch_state']['values']

DISPATCH_ATTEMPT_FIELDS = tuple(SHAPES['dispatch_attempt']['fields'])
DISPATCH_ATTEMPT_REQUIRED = frozenset(SHAPES['dispatch_attempt']['required'])
DISPATCH_ATTEMPT_VALUES = SHAPES['dispatch_attempt']['values']

DISPATCH_RECORD_FIELDS = tuple(SHAPES['dispatch_record']['fields'])
DISPATCH_RECORD_REQUIRED = frozenset(SHAPES['dispatch_record']['required'])
DISPATCH_RECORD_VALUES = SHAPES['dispatch_record']['values']

DISPATCH_STORED_SUCCESS_FIELDS = tuple(SHAPES['dispatch_stored_success']['fields'])
DISPATCH_STORED_SUCCESS_REQUIRED = frozenset(SHAPES['dispatch_stored_success']['required'])
DISPATCH_STORED_SUCCESS_VALUES = SHAPES['dispatch_stored_success']['values']

DISPATCH_COMMITTED_RECORD_FIELDS = tuple(SHAPES['dispatch_committed_record']['fields'])
DISPATCH_COMMITTED_RECORD_REQUIRED = frozenset(SHAPES['dispatch_committed_record']['required'])
DISPATCH_COMMITTED_RECORD_VALUES = SHAPES['dispatch_committed_record']['values']

DISPATCH_LAUNCH_RECORD_FIELDS = tuple(SHAPES['dispatch_launch_record']['fields'])
DISPATCH_LAUNCH_RECORD_REQUIRED = frozenset(SHAPES['dispatch_launch_record']['required'])
DISPATCH_LAUNCH_RECORD_VALUES = SHAPES['dispatch_launch_record']['values']

DISPATCH_RESULT_RECORD_FIELDS = tuple(SHAPES['dispatch_result_record']['fields'])
DISPATCH_RESULT_RECORD_REQUIRED = frozenset(SHAPES['dispatch_result_record']['required'])
DISPATCH_RESULT_RECORD_VALUES = SHAPES['dispatch_result_record']['values']

DISPATCH_RESULT_SUCCESS_FIELDS = tuple(SHAPES['dispatch_result_success']['fields'])
DISPATCH_RESULT_SUCCESS_REQUIRED = frozenset(SHAPES['dispatch_result_success']['required'])
DISPATCH_RESULT_SUCCESS_VALUES = SHAPES['dispatch_result_success']['values']

DISPATCH_RESULT_PROJECTION_FIELDS = tuple(SHAPES['dispatch_result_projection']['fields'])
DISPATCH_RESULT_PROJECTION_REQUIRED = frozenset(SHAPES['dispatch_result_projection']['required'])
DISPATCH_RESULT_PROJECTION_VALUES = SHAPES['dispatch_result_projection']['values']

DISPATCH_TRANSITION_SUCCESS_FIELDS = tuple(SHAPES['dispatch_transition_success']['fields'])
DISPATCH_TRANSITION_SUCCESS_REQUIRED = frozenset(SHAPES['dispatch_transition_success']['required'])
DISPATCH_TRANSITION_SUCCESS_VALUES = SHAPES['dispatch_transition_success']['values']

DISPATCH_RETIREMENT_DISPATCH_FIELDS = tuple(SHAPES['dispatch_retirement_dispatch']['fields'])
DISPATCH_RETIREMENT_DISPATCH_REQUIRED = frozenset(SHAPES['dispatch_retirement_dispatch']['required'])
DISPATCH_RETIREMENT_DISPATCH_VALUES = SHAPES['dispatch_retirement_dispatch']['values']

DISPATCH_REPLACEMENT_DISPATCH_FIELDS = tuple(SHAPES['dispatch_replacement_dispatch']['fields'])
DISPATCH_REPLACEMENT_DISPATCH_REQUIRED = frozenset(SHAPES['dispatch_replacement_dispatch']['required'])
DISPATCH_REPLACEMENT_DISPATCH_VALUES = SHAPES['dispatch_replacement_dispatch']['values']

DISPATCH_JOIN_CONTENT_FIELDS = tuple(SHAPES['dispatch_join_content']['fields'])
DISPATCH_JOIN_CONTENT_REQUIRED = frozenset(SHAPES['dispatch_join_content']['required'])
DISPATCH_JOIN_CONTENT_VALUES = SHAPES['dispatch_join_content']['values']

DISPATCH_RETIRE_REQUEST_FIELDS = tuple(SHAPES['dispatch_retire_request']['fields'])
DISPATCH_RETIRE_REQUEST_REQUIRED = frozenset(SHAPES['dispatch_retire_request']['required'])
DISPATCH_RETIRE_REQUEST_VALUES = SHAPES['dispatch_retire_request']['values']

DISPATCH_REPLACE_REQUEST_FIELDS = tuple(SHAPES['dispatch_replace_request']['fields'])
DISPATCH_REPLACE_REQUEST_REQUIRED = frozenset(SHAPES['dispatch_replace_request']['required'])
DISPATCH_REPLACE_REQUEST_VALUES = SHAPES['dispatch_replace_request']['values']

DISPATCH_JOIN_SUCCESS_FIELDS = tuple(SHAPES['dispatch_join_success']['fields'])
DISPATCH_JOIN_SUCCESS_REQUIRED = frozenset(SHAPES['dispatch_join_success']['required'])
DISPATCH_JOIN_SUCCESS_VALUES = SHAPES['dispatch_join_success']['values']

DISPATCH_LAUNCH_FIELDS = tuple(SHAPES['dispatch_launch']['fields'])
DISPATCH_LAUNCH_REQUIRED = frozenset(SHAPES['dispatch_launch']['required'])
DISPATCH_LAUNCH_VALUES = SHAPES['dispatch_launch']['values']

DISPATCH_OUTCOME_FIELDS = tuple(SHAPES['dispatch_outcome']['fields'])
DISPATCH_OUTCOME_REQUIRED = frozenset(SHAPES['dispatch_outcome']['required'])
DISPATCH_OUTCOME_VALUES = SHAPES['dispatch_outcome']['values']

TICKET_ASSIGNMENT_SECTIONS_FIELDS = tuple(SHAPES['ticket_assignment_sections']['fields'])
TICKET_ASSIGNMENT_SECTIONS_REQUIRED = frozenset(SHAPES['ticket_assignment_sections']['required'])
TICKET_ASSIGNMENT_SECTIONS_VALUES = SHAPES['ticket_assignment_sections']['values']

TICKET_FRONTMATTER_FIELDS = tuple(SHAPES['ticket_frontmatter']['fields'])
TICKET_FRONTMATTER_REQUIRED = frozenset(SHAPES['ticket_frontmatter']['required'])
TICKET_FRONTMATTER_VALUES = SHAPES['ticket_frontmatter']['values']

DONE_BINDING_FIELDS = tuple(SHAPES['done_binding']['fields'])
DONE_BINDING_REQUIRED = frozenset(SHAPES['done_binding']['required'])
DONE_BINDING_VALUES = SHAPES['done_binding']['values']

EXECUTOR_RESULT_FIELDS = tuple(SHAPES['executor_result']['fields'])
EXECUTOR_RESULT_REQUIRED = frozenset(SHAPES['executor_result']['required'])
EXECUTOR_RESULT_VALUES = SHAPES['executor_result']['values']

VERDICT_CRITERION_FIELDS = tuple(SHAPES['verdict_criterion']['fields'])
VERDICT_CRITERION_REQUIRED = frozenset(SHAPES['verdict_criterion']['required'])
VERDICT_CRITERION_VALUES = SHAPES['verdict_criterion']['values']

WORKLOG_VIEW_FIELDS = tuple(SHAPES['worklog_view']['fields'])
WORKLOG_VIEW_REQUIRED = frozenset(SHAPES['worklog_view']['required'])
WORKLOG_VIEW_VALUES = SHAPES['worklog_view']['values']

PACK_CELLS_FIELDS = tuple(SHAPES['pack_cells']['fields'])
PACK_CELLS_REQUIRED = frozenset(SHAPES['pack_cells']['required'])
PACK_CELLS_VALUES = SHAPES['pack_cells']['values']

SHEET_FRONTMATTER_FIELDS = tuple(SHAPES['sheet_frontmatter']['fields'])
SHEET_FRONTMATTER_REQUIRED = frozenset(SHAPES['sheet_frontmatter']['required'])
SHEET_FRONTMATTER_VALUES = SHAPES['sheet_frontmatter']['values']

SHEET_SECTIONS_FIELDS = tuple(SHAPES['sheet_sections']['fields'])
SHEET_SECTIONS_REQUIRED = frozenset(SHAPES['sheet_sections']['required'])
SHEET_SECTIONS_VALUES = SHAPES['sheet_sections']['values']

def fields(name: str) -> tuple:
    """Return the declared field order for one shape."""
    return tuple(SHAPES[name]['fields'])

def required(name: str) -> frozenset:
    """Return the required fields for one shape."""
    return frozenset(SHAPES[name]['required'])

