"""Ordered public facade for every route constant this package can reach.

The private support catalogs own endpoint declarations by access class, and
the contract support module owns their immutable shapes and public client
credentials. This facade restores the one auditable ordered allowlist callers
have always imported. It imports no mechanism and reaches no network.

:mod:`.transport` admits methods, opens sockets, attaches credentials, and
re-exports every public name below under its established address. The suite,
adapters, and CLI therefore continue to reach route data through transport
without depending on the private catalog layout.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Tuple

from ._support.route_catalog_k0 import K0_ROUTE_CONSTANTS as _K0_ROUTE_CONSTANTS
from ._support.route_catalog_k1_k4 import (
    K1_K4_ROUTE_CONSTANTS as _K1_K4_ROUTE_CONSTANTS,
    OFFLINE_ROUTE_CONSTANTS as _OFFLINE_ROUTE_CONSTANTS,
)
from ._support.route_contracts import (
    ARCTIC_SHIFT_ORIGIN,
    ARCTIC_SHIFT_POSTS_ROUTE,
    ARXIV_QUERY_ROUTE,
    BING_NEWS_RSS_ROUTE,
    BING_RSS_ROUTE,
    BLUESKY_AUTHOR_FEED_ROUTE,
    BLUESKY_SEARCH_POSTS_ROUTE,
    CREDENTIAL_PLACEMENTS,
    CROSSREF_WORKS_ROUTE,
    DDG_HTML_ROUTE,
    FAKE_OFFLINE_ROUTE,
    FXTWITTER_API_ROUTE,
    GDELT_DOC_ROUTE,
    GITHUB_REST_ROUTE,
    GITHUB_SEARCH_ROUTE,
    GOOGLE_NEWS_RSS_ROUTE,
    HEADER_PLACEMENT,
    HN_ALGOLIA_ITEM_ROUTE,
    HN_ALGOLIA_SEARCH_ROUTE,
    HN_FIREBASE_ITEM_ROUTE,
    INSTAGRAM_WEB_APP_ID,
    INSTAGRAM_WEB_PROFILE_ROUTE,
    JSON_CONTENT_TYPE,
    KALSHI_MARKETS_ROUTE,
    LINKEDIN_JOBS_GUEST_SEARCH_ROUTE,
    LINKEDIN_PUBLIC_PROFILE_ROUTE,
    MANIFOLD_MARKETS_ROUTE,
    OPEN_ORIGIN,
    OPENALEX_WORKS_ROUTE,
    POLYMARKET_GAMMA_ROUTE,
    PUBLIC_CLIENT_CREDENTIALS,
    PUBLIC_PAGE_ARTICLE_ROUTE,
    PUBLIC_PAGE_CONTROL_ROUTE,
    QUERY_PLACEMENT,
    REDDIT_FEED_ROUTE,
    REDDIT_SHREDDIT_COMMENTS_ROUTE,
    REDDIT_SHREDDIT_LISTING_ROUTE,
    REDDIT_SHREDDIT_SEARCH_ROUTE,
    REDDIT_SHREDDIT_SUBREDDIT_SEARCH_ROUTE,
    REDDIT_SITE_ORIGIN,
    SOUNDCLOUD_OEMBED_ROUTE,
    SPOTIFY_OEMBED_ROUTE,
    STACKEXCHANGE_SEARCH_ROUTE,
    STOCKTWITS_STREAM_ROUTE,
    STOCKTWITS_SYMBOL_SEARCH_ROUTE,
    TIKTOK_OEMBED_ROUTE,
    TIKTOK_PROFILE_PAGE_ROUTE,
    TIKTOK_VIDEO_PAGE_ROUTE,
    VIMEO_OEMBED_ROUTE,
    WEB_PAGE_OPEN_ROUTE,
    WIKIMEDIA_PAGEVIEWS_ROUTE,
    X_GUEST_ACTIVATE_ROUTE,
    X_GUEST_GRAPHQL_ROUTE,
    X_GUEST_PUBLIC_BEARER,
    X_PUBLISH_OEMBED_ROUTE,
    X_SYNDICATION_TIMELINE_ROUTE,
    YOUTUBE_CHANNEL_FEED_ROUTE,
    YOUTUBE_INNERTUBE_ROUTE,
    YOUTUBE_INNERTUBE_WEB_KEY,
    YOUTUBE_OEMBED_ROUTE,
    YOUTUBE_TIMEDTEXT_ROUTE,
    PublicClientCredential,
    RouteConstant,
)


_ROUTE_CATALOG = {
    **_K0_ROUTE_CONSTANTS,
    **_K1_K4_ROUTE_CONSTANTS,
    **_OFFLINE_ROUTE_CONSTANTS,
}

# Order is part of the public table: schedulers, smoke reports, and fixtures
# traverse this mapping without sorting. Keep the historical sequence explicit
# here even though declarations are grouped by access class in private support.
ROUTE_CONSTANTS: Dict[str, RouteConstant] = {
    DDG_HTML_ROUTE: _ROUTE_CATALOG[DDG_HTML_ROUTE],
    BING_RSS_ROUTE: _ROUTE_CATALOG[BING_RSS_ROUTE],
    BING_NEWS_RSS_ROUTE: _ROUTE_CATALOG[BING_NEWS_RSS_ROUTE],
    GOOGLE_NEWS_RSS_ROUTE: _ROUTE_CATALOG[GOOGLE_NEWS_RSS_ROUTE],
    WEB_PAGE_OPEN_ROUTE: _ROUTE_CATALOG[WEB_PAGE_OPEN_ROUTE],
    ARCTIC_SHIFT_POSTS_ROUTE: _ROUTE_CATALOG[ARCTIC_SHIFT_POSTS_ROUTE],
    REDDIT_SHREDDIT_LISTING_ROUTE: _ROUTE_CATALOG[REDDIT_SHREDDIT_LISTING_ROUTE],
    REDDIT_SHREDDIT_SEARCH_ROUTE: _ROUTE_CATALOG[REDDIT_SHREDDIT_SEARCH_ROUTE],
    REDDIT_SHREDDIT_SUBREDDIT_SEARCH_ROUTE: _ROUTE_CATALOG[
        REDDIT_SHREDDIT_SUBREDDIT_SEARCH_ROUTE
    ],
    REDDIT_SHREDDIT_COMMENTS_ROUTE: _ROUTE_CATALOG[REDDIT_SHREDDIT_COMMENTS_ROUTE],
    YOUTUBE_TIMEDTEXT_ROUTE: _ROUTE_CATALOG[YOUTUBE_TIMEDTEXT_ROUTE],
    HN_ALGOLIA_ITEM_ROUTE: _ROUTE_CATALOG[HN_ALGOLIA_ITEM_ROUTE],
    POLYMARKET_GAMMA_ROUTE: _ROUTE_CATALOG[POLYMARKET_GAMMA_ROUTE],
    KALSHI_MARKETS_ROUTE: _ROUTE_CATALOG[KALSHI_MARKETS_ROUTE],
    MANIFOLD_MARKETS_ROUTE: _ROUTE_CATALOG[MANIFOLD_MARKETS_ROUTE],
    STOCKTWITS_STREAM_ROUTE: _ROUTE_CATALOG[STOCKTWITS_STREAM_ROUTE],
    STOCKTWITS_SYMBOL_SEARCH_ROUTE: _ROUTE_CATALOG[STOCKTWITS_SYMBOL_SEARCH_ROUTE],
    BLUESKY_SEARCH_POSTS_ROUTE: _ROUTE_CATALOG[BLUESKY_SEARCH_POSTS_ROUTE],
    BLUESKY_AUTHOR_FEED_ROUTE: _ROUTE_CATALOG[BLUESKY_AUTHOR_FEED_ROUTE],
    FXTWITTER_API_ROUTE: _ROUTE_CATALOG[FXTWITTER_API_ROUTE],
    X_GUEST_ACTIVATE_ROUTE: _ROUTE_CATALOG[X_GUEST_ACTIVATE_ROUTE],
    X_SYNDICATION_TIMELINE_ROUTE: _ROUTE_CATALOG[X_SYNDICATION_TIMELINE_ROUTE],
    X_GUEST_GRAPHQL_ROUTE: _ROUTE_CATALOG[X_GUEST_GRAPHQL_ROUTE],
    LINKEDIN_JOBS_GUEST_SEARCH_ROUTE: _ROUTE_CATALOG[LINKEDIN_JOBS_GUEST_SEARCH_ROUTE],
    LINKEDIN_PUBLIC_PROFILE_ROUTE: _ROUTE_CATALOG[LINKEDIN_PUBLIC_PROFILE_ROUTE],
    YOUTUBE_INNERTUBE_ROUTE: _ROUTE_CATALOG[YOUTUBE_INNERTUBE_ROUTE],
    INSTAGRAM_WEB_PROFILE_ROUTE: _ROUTE_CATALOG[INSTAGRAM_WEB_PROFILE_ROUTE],
    HN_ALGOLIA_SEARCH_ROUTE: _ROUTE_CATALOG[HN_ALGOLIA_SEARCH_ROUTE],
    HN_FIREBASE_ITEM_ROUTE: _ROUTE_CATALOG[HN_FIREBASE_ITEM_ROUTE],
    GITHUB_REST_ROUTE: _ROUTE_CATALOG[GITHUB_REST_ROUTE],
    GITHUB_SEARCH_ROUTE: _ROUTE_CATALOG[GITHUB_SEARCH_ROUTE],
    REDDIT_FEED_ROUTE: _ROUTE_CATALOG[REDDIT_FEED_ROUTE],
    YOUTUBE_CHANNEL_FEED_ROUTE: _ROUTE_CATALOG[YOUTUBE_CHANNEL_FEED_ROUTE],
    PUBLIC_PAGE_ARTICLE_ROUTE: _ROUTE_CATALOG[PUBLIC_PAGE_ARTICLE_ROUTE],
    PUBLIC_PAGE_CONTROL_ROUTE: _ROUTE_CATALOG[PUBLIC_PAGE_CONTROL_ROUTE],
    GDELT_DOC_ROUTE: _ROUTE_CATALOG[GDELT_DOC_ROUTE],
    STACKEXCHANGE_SEARCH_ROUTE: _ROUTE_CATALOG[STACKEXCHANGE_SEARCH_ROUTE],
    WIKIMEDIA_PAGEVIEWS_ROUTE: _ROUTE_CATALOG[WIKIMEDIA_PAGEVIEWS_ROUTE],
    OPENALEX_WORKS_ROUTE: _ROUTE_CATALOG[OPENALEX_WORKS_ROUTE],
    CROSSREF_WORKS_ROUTE: _ROUTE_CATALOG[CROSSREF_WORKS_ROUTE],
    ARXIV_QUERY_ROUTE: _ROUTE_CATALOG[ARXIV_QUERY_ROUTE],
    TIKTOK_VIDEO_PAGE_ROUTE: _ROUTE_CATALOG[TIKTOK_VIDEO_PAGE_ROUTE],
    TIKTOK_PROFILE_PAGE_ROUTE: _ROUTE_CATALOG[TIKTOK_PROFILE_PAGE_ROUTE],
    YOUTUBE_OEMBED_ROUTE: _ROUTE_CATALOG[YOUTUBE_OEMBED_ROUTE],
    VIMEO_OEMBED_ROUTE: _ROUTE_CATALOG[VIMEO_OEMBED_ROUTE],
    SPOTIFY_OEMBED_ROUTE: _ROUTE_CATALOG[SPOTIFY_OEMBED_ROUTE],
    SOUNDCLOUD_OEMBED_ROUTE: _ROUTE_CATALOG[SOUNDCLOUD_OEMBED_ROUTE],
    TIKTOK_OEMBED_ROUTE: _ROUTE_CATALOG[TIKTOK_OEMBED_ROUTE],
    X_PUBLISH_OEMBED_ROUTE: _ROUTE_CATALOG[X_PUBLISH_OEMBED_ROUTE],
    FAKE_OFFLINE_ROUTE: _ROUTE_CATALOG[FAKE_OFFLINE_ROUTE],
}

del _ROUTE_CATALOG
