"""Render the lifecycle table from executable transition declarations."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys


# This walk locates `scripts/` so it can be put on sys.path for the bare
# `import tickets_lifecycle` below (the flat-layout import spelling);
# `scripts._bootstrap.ROOT` is not reachable until that insert has run.
ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = ROOT / "scripts"
TARGET = ROOT / "docs" / "lifecycle.md"
if str(SCRIPTS) not in sys.path:
    sys.path.insert(0, str(SCRIPTS))

import tickets_commands  # noqa: E402
import tickets_lifecycle  # noqa: E402


HEADER = """# Ticket lifecycle

Generated by tools/render_lifecycle.py from the executable declarations in
`scripts/tickets_transitions.py` as exposed by `scripts/tickets_lifecycle.py`.
Do not edit this file by hand. The validator refuses any byte drift.

| predecessor state | event | authorized actor | required predecessor record | resulting state | owning contract | owning rule |
| --- | --- | --- | --- | --- | --- | --- |
"""


CALLER = "caller"


class UnroutedCallerEvent(RuntimeError):
    """A `caller` row names an event no subcommand performs."""


def unrouted_caller_events(rows) -> list:
    """The `caller` rows whose event `tickets.py` does not route.

    `caller` names the command line, so such a row promises a reader a
    command to run. An event that only some other command performs
    names that command as its actor instead; a `caller` row for it
    sends the reader after a subcommand that answers `unknown
    subcommand`.
    """

    return sorted({
        row.event for row in rows
        if row.actor == CALLER
        and row.event.split()[0] not in tickets_commands.SUBCOMMAND_USAGE
    })


def _cell(value: str) -> str:
    """One table cell: the delimiter escaped, because a value may carry it.

    An actor naming two commands spells them `do|judge`, and an unescaped
    pipe there would end the cell and shift every column after it.
    """

    return value.replace("|", "\\|")


def _link(path: str) -> str:
    return f"[{path}](../{path})"


def render() -> str:
    rows = tickets_lifecycle.lifecycle_rows()
    unrouted = unrouted_caller_events(rows)
    if unrouted:
        raise UnroutedCallerEvent(
            "caller rows name unrouted events: " + ", ".join(unrouted)
        )
    lines = [HEADER]
    for row in rows:
        lines.append(
            f'| <a id="{row.anchor}"></a> `{row.predecessor}` | `{row.event}` | '
            f"{_cell(row.actor)} | {row.required_record} | `{row.result}` | "
            f"{_link(row.contract)} | {_link(row.rule)} |\n"
        )
    return "".join(lines)


def is_current(path: Path = TARGET) -> bool:
    try:
        return path.read_text(encoding="utf-8") == render()
    except OSError:
        return False


def write(path: Path = TARGET) -> None:
    # Render before opening so a renderer that reads its target can never be
    # truncated first. open(..., newline="") rather than write_text(newline=):
    # the keyword is 3.10+ and the floor is 3.9.
    document = render()
    with open(path, "w", encoding="utf-8", newline="") as stream:
        stream.write(document)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="refuse rendered-byte drift")
    parser.add_argument("--output", type=Path, default=TARGET)
    args = parser.parse_args(argv)
    if args.check:
        if is_current(args.output):
            print(f"lifecycle table is current: {args.output}")
            return 0
        print(f"lifecycle table drift: run {Path(__file__).name}")
        return 1
    write(args.output)
    print(f"wrote lifecycle table: {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
