"""Render the lifecycle table from executable transition declarations."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = ROOT / "scripts"
TARGET = ROOT / "docs" / "lifecycle.md"
if str(SCRIPTS) not in sys.path:
    sys.path.insert(0, str(SCRIPTS))

import tickets_lifecycle  # noqa: E402


HEADER = """# Ticket lifecycle

Generated by tools/render_lifecycle.py from the executable declarations in
`scripts/tickets_transitions.py` as exposed by `scripts/tickets_lifecycle.py`.
Do not edit this file by hand. The validator refuses any byte drift.

| predecessor state | event | authorized actor | required predecessor record | resulting state | owning contract | owning rule |
| --- | --- | --- | --- | --- | --- | --- |
"""


def _link(path: str) -> str:
    return f"[{path}](../{path})"


def render() -> str:
    lines = [HEADER]
    for row in tickets_lifecycle.lifecycle_rows():
        lines.append(
            f'| <a id="{row.anchor}"></a> `{row.predecessor}` | `{row.event}` | '
            f"{row.actor} | {row.required_record} | `{row.result}` | "
            f"{_link(row.contract)} | {_link(row.rule)} |\n"
        )
    return "".join(lines)


def is_current(path: Path = TARGET) -> bool:
    try:
        return path.read_text(encoding="utf-8") == render()
    except OSError:
        return False


def write(path: Path = TARGET) -> None:
    path.write_text(render(), encoding="utf-8", newline="")


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="refuse rendered-byte drift")
    parser.add_argument("--output", type=Path, default=TARGET)
    args = parser.parse_args(argv)
    if args.check:
        if is_current(args.output):
            print(f"lifecycle table is current: {args.output}")
            return 0
        print(f"lifecycle table drift: run {Path(__file__).name}")
        return 1
    write(args.output)
    print(f"wrote lifecycle table: {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
