"""Render T0 shape declarations into validator data and contract sections."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import pprint
import re


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "contracts" / "shapes.json"
VALIDATOR = ROOT / "scripts" / "tickets_shapes.py"
CONTRACTS_DIR = ROOT / "contracts"
BEGIN = "<!-- BEGIN GENERATED T0 SHAPES -->"
END = "<!-- END GENERATED T0 SHAPES -->"


def _load(path: Path = SOURCE) -> dict:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise ValueError(f"{path}: unreadable shape declarations: {error}") from error
    if not isinstance(value, dict) or value.get("schema_version") != 1:
        raise ValueError(f"{path}: unsupported shape declaration schema")
    shapes = value.get("shapes")
    if not isinstance(shapes, list) or not shapes:
        raise ValueError(f"{path}: shapes must be a non-empty array")
    names = set()
    for item in shapes:
        if not isinstance(item, dict) or not isinstance(item.get("name"), str):
            raise ValueError(f"{path}: every shape needs a name")
        name = item["name"]
        if name in names:
            raise ValueError(f"{path}: duplicate shape {name}")
        names.add(name)
        if not isinstance(item.get("contract"), str) or not item["contract"]:
            raise ValueError(f"{path}: shape {name} has no contract")
        fields = item.get("fields")
        required = item.get("required")
        if not isinstance(fields, list) or not fields or any(
            not isinstance(field, str) or not field for field in fields
        ) or len(fields) != len(set(fields)):
            raise ValueError(f"{path}: shape {name} has invalid or repeated fields")
        if (
            not isinstance(required, list)
            or len(required) != len(set(required))
            or not set(required) <= set(fields)
        ):
            raise ValueError(f"{path}: shape {name} has invalid required fields")
        values = item.get("values", {})
        if not isinstance(values, dict) or not set(values) <= set(fields):
            raise ValueError(f"{path}: shape {name} has invalid value declarations")
        for field, allowed in values.items():
            if (
                not isinstance(allowed, list)
                or len(allowed) != len(set(allowed))
                or any(not isinstance(value, str) or not value for value in allowed)
            ):
                raise ValueError(
                    f"{path}: shape {name} has invalid values for {field}"
                )
    constants = value.get("constants", {})
    if not isinstance(constants, dict) or any(
        not isinstance(key, str) or not key or not isinstance(item, str) or not item
        for key, item in constants.items()
    ):
        raise ValueError(f"{path}: constants must be a string mapping")
    return value


def _shape_data(source: Path = SOURCE) -> list[dict]:
    return _load(source)["shapes"]


def declarations(source: Path = SOURCE) -> tuple[str, ...]:
    return tuple(item["name"] for item in _shape_data(source))


def declaration(name: str, source: Path = SOURCE) -> dict:
    for item in _shape_data(source):
        if item["name"] == name:
            return item
    raise KeyError(name)


def contracts(source: Path = SOURCE) -> tuple[str, ...]:
    return tuple(sorted({item["contract"] for item in _shape_data(source)}))


def _constant(name: str) -> str:
    return re.sub(r"[^A-Za-z0-9]+", "_", name).upper()


def render_validator(source: Path = SOURCE) -> str:
    """Return the generated stdlib-only module consumed by ticket validators."""

    source_data = _shape_data(source)
    source_document = _load(source)
    shapes = {
        item["name"]: {
            "contract": item["contract"],
            "fields": tuple(item["fields"]),
            "required": tuple(item["required"]),
            "values": {
                key: tuple(values) for key, values in item.get("values", {}).items()
            },
        }
        for item in source_data
    }
    lines = [
        '"""Generated T0 shape data; edit contracts/shapes.json instead."""',
        "# GENERATED BY tools/render_shapes.py; DO NOT EDIT.",
        "from __future__ import annotations",
        "",
        "CONSTANTS = ",
    ]
    lines[-1] += pprint.pformat(source_document.get("constants", {}), width=160, sort_dicts=True)
    lines.extend([
        "",
        "SHAPES = ",
    ])
    # pprint emits Python literals and keeps insertion order deterministic.
    encoded = pprint.pformat(shapes, width=160, sort_dicts=True)
    lines[-1] += encoded
    lines.append("")
    for name in sorted(source_document.get("constants", {})):
        lines.append(f"{_constant(name)} = CONSTANTS[{name!r}]")
    lines.append("")
    for item in source_data:
        const = _constant(item["name"])
        lines.append(f"{const}_FIELDS = tuple(SHAPES[{item['name']!r}]['fields'])")
        lines.append(f"{const}_REQUIRED = frozenset(SHAPES[{item['name']!r}]['required'])")
        lines.append(f"{const}_VALUES = SHAPES[{item['name']!r}]['values']")
        lines.append("")
    lines.extend([
        "def fields(name: str) -> tuple:",
        '    """Return the declared field order for one shape."""',
        "    return tuple(SHAPES[name]['fields'])",
        "",
        "def required(name: str) -> frozenset:",
        '    """Return the required fields for one shape."""',
        "    return frozenset(SHAPES[name]['required'])",
        "",
    ])
    return "\n".join(lines) + "\n"


def render_contract(contract: str, source: Path = SOURCE) -> str:
    """Render the generated shape section for one contract filename."""

    contract_name = Path(contract).name
    selected = [item for item in _shape_data(source) if item["contract"] == contract_name]
    if not selected:
        raise KeyError(contract)
    lines = [
        BEGIN + "\n",
        "## Generated T0 shape\n\n",
        "GENERATED BY tools/render_shapes.py from `contracts/shapes.json` for "
        f"`contracts/{contract_name}`. "
        "Rendered T0 shape; declaration drift is a validation error.\n\n",
    ]
    for item in selected:
        lines.append(f"### `{item['name']}`\n\n")
        lines.append("| field | required | declared values |\n| --- | --- | --- |\n")
        values = item.get("values", {})
        for field in item["fields"]:
            allowed = ", ".join(f"`{value}`" for value in values.get(field, ())) or "—"
            required = "yes" if field in item["required"] else "no"
            lines.append(f"| `{field}` | {required} | {allowed} |\n")
        lines.append("\n")
    lines.append(END + "\n")
    return "".join(lines)


def _replace_section(text: str, section: str) -> str:
    pattern = re.compile(
        re.escape(BEGIN) + r"\n.*?" + re.escape(END) + r"\n?",
        re.DOTALL,
    )
    if pattern.search(text):
        return pattern.sub(section, text, count=1)
    marker = "\n## T0 supersession\n"
    if marker in text:
        return text.replace(marker, "\n" + section + marker, 1)
    return text.rstrip() + "\n\n" + section


def render_contract_document(path: Path, source: Path = SOURCE) -> str:
    return _replace_section(
        path.read_text(encoding="utf-8"), render_contract(path.name, source)
    )


def validator_is_current(path: Path = VALIDATOR, source: Path = SOURCE) -> bool:
    try:
        return path.read_text(encoding="utf-8") == render_validator(source)
    except OSError:
        return False


def contract_is_current(path: Path, source: Path = SOURCE) -> bool:
    try:
        return path.read_text(encoding="utf-8") == render_contract_document(path, source)
    except (OSError, KeyError):
        return False


def write() -> None:
    VALIDATOR.write_text(render_validator(), encoding="utf-8", newline="")
    for name in contracts():
        path = CONTRACTS_DIR / name
        path.write_text(render_contract_document(path), encoding="utf-8", newline="")


def check(root: Path = ROOT) -> None:
    source = root / "contracts" / SOURCE.name
    validator = root / "scripts" / VALIDATOR.name
    contracts_dir = root / "contracts"
    if not validator_is_current(validator, source):
        raise ValueError(f"{validator}: generated validator is stale; run tools/render_shapes.py --write")
    for name in contracts(source):
        path = contracts_dir / name
        if not contract_is_current(path, source):
            raise ValueError(f"{path}: generated shape section is stale; run tools/render_shapes.py --write")


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true", help="write generated consumers")
    mode.add_argument("--check", action="store_true", help="refuse generated-byte drift")
    args = parser.parse_args(argv)
    try:
        if args.write or not args.check:
            write()
            print("T0 shape consumers rendered")
        else:
            check()
            print("T0 shape consumers are current")
    except (OSError, KeyError, ValueError) as error:
        parser.exit(1, f"error: {error}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
